In [41]:
import numpy as np

data=np.load('data.npy')
target=np.load('target.npy')

In [42]:
print(data.shape)
print(target.shape,target)

(270, 64)
(270,) [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3]


In [43]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.2)

In [44]:
print(train_data.shape,train_target.shape)
print(test_data.shape,test_target.shape)

(216, 64) (216,)
(54, 64) (54,)


In [45]:
print(test_data,test_target)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 252 255 ... 255 255 254]
 [254 255 254 ... 255 255 255]
 [255 255 255 ... 255 143   0]] [0 0 0 3 1 0 1 0 3 1 3 2 1 3 2 2 2 2 2 3 0 0 3 1 1 2 3 0 3 1 3 2 0 3 0 2 1
 0 1 3 2 3 3 3 0 1 2 3 2 2 0 2 1 3]


In [46]:
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier() #load KNN algorithm into model

In [47]:
model.fit(train_data,train_target) #training the KNN model using traininig data and target

KNeighborsClassifier()

In [48]:
predicted_target=model.predict(test_data) #getting predictions from the model
print(predicted_target)

[0 3 0 0 1 0 1 0 3 1 3 2 1 3 2 2 2 1 0 3 0 0 3 1 1 2 3 0 2 0 3 2 0 3 0 2 1
 0 0 3 2 3 3 3 0 1 0 3 2 2 0 2 1 0]


In [49]:
print(test_target)

[0 0 0 3 1 0 1 0 3 1 3 2 1 3 2 2 2 2 2 3 0 0 3 1 1 2 3 0 3 1 3 2 0 3 0 2 1
 0 1 3 2 3 3 3 0 1 2 3 2 2 0 2 1 3]


In [50]:
from sklearn.metrics import accuracy_score
acc= accuracy_score(test_target,predicted_target)
print("Accuracy:",acc)

Accuracy: 0.8333333333333334


In [51]:
from sklearn.metrics import classification_report

classi_report=classification_report(test_target,predicted_target)
print('Classification Report:', classi_report)

Classification Report:               precision    recall  f1-score   support

           0       0.67      0.92      0.77        13
           1       0.90      0.82      0.86        11
           2       0.92      0.79      0.85        14
           3       0.93      0.81      0.87        16

    accuracy                           0.83        54
   macro avg       0.85      0.83      0.84        54
weighted avg       0.86      0.83      0.84        54



In [52]:
import joblib
joblib.dump(model,'sinhala_character-knn.sav')

['sinhala_character-knn.sav']